version: '3'
services:
  orders-service:
    build:
      dockerfile: Dockerfile
      context: ./orders-service
    ports:
      - 5000:5000
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  billings-service:
    build:
      dockerfile: Dockerfile
      context: ./billings-service
    ports:
      - 5001:5000
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  redis:
    image: redis:latest

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181