version: '3'
services:
  orders-service:
    build:
      dockerfile: Dockerfile
      context: ./orders-service
    ports:
      - 5000:5000
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  billings-service:
    build:
      dockerfile: Dockerfile
      context: ./billings-service
    ports:
      - 5001:5000
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  redis:
    image: redis:latest

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#  kafka:
#    image: confluentinc/cp-kafka:6.2.0
#    ports:
#      - 9092:9092
#    environment:
#     KAFKA_BROKER_ID: 1
#     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:9092
#     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#         - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
#    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#    - KAFKA_CLIENTS_SESSION_TIMEOUT=60000
#    - JAVA_OPTS=-Xmx1024m -Xms512m 
#    depends_on:
#      - zookeeper
#
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9092
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    depends_on:
      - kafka-init
      - zookeeper
  kafka-init:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9092
    command: ["bash", "-c", "echo 'init'"]
